# Generated by Django 2.2.2 on 2019-06-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='High_risk_traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.IntegerField()),
                ('src_ip', models.CharField(max_length=15)),
                ('des_ip', models.CharField(max_length=15)),
                ('sport', models.IntegerField()),
                ('dsport', models.IntegerField()),
                ('load', models.CharField(max_length=1024)),
            ],
        ),
    ]
