# Generated by Django 2.2.2 on 2019-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_risk_traffic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
