# Generated by Django 2.2.2 on 2019-06-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_recognition', '0002_auto_20190609_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='high_risk_traffic',
            name='load',
        ),
    ]
