# Generated by Django 2.2.2 on 2019-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_recognition', '0003_remove_high_risk_traffic_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_risk_traffic',
            name='dsport',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='high_risk_traffic',
            name='sport',
            field=models.CharField(max_length=10),
        ),
    ]
