# Generated by Django 2.2.2 on 2019-06-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_recognition', '0004_auto_20190609_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='high_risk_traffic',
            old_name='des_ip',
            new_name='dst_ip',
        ),
    ]
