# Generated by Django 2.2.2 on 2019-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_recognition', '0006_auto_20190609_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='black_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
