# Generated by Django 2.2.2 on 2019-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_recognition', '0007_black_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('str', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
